"""Project-wide enums and constants."""
from __future__ import annotations

from enum import Enum


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NEUTRAL = "NEUTRAL"


class SetupType(str, Enum):
    SWEEP_REVERSAL = "SWEEP_REVERSAL"
    TREND_CONTINUATION = "TREND_CONTINUATION"
    FLAG_BREAKOUT = "FLAG_BREAKOUT"


class Regime(str, Enum):
    TRENDING_BULLISH = "TRENDING_BULLISH"
    TRENDING_BEARISH = "TRENDING_BEARISH"
    RANGING = "RANGING"
    VOLATILE_CRISIS = "VOLATILE_CRISIS"
    TRANSITIONING = "TRANSITIONING"
    UNKNOWN = "UNKNOWN"


class MacroBias(str, Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"
    CONFLICTING = "CONFLICTING"


class Session(str, Enum):
    ASIAN = "ASIAN"
    LONDON = "LONDON"
    NEW_YORK = "NEW_YORK"
    NY_OVERLAP = "NY_OVERLAP"
    DEAD_ZONE = "DEAD_ZONE"
    WEEKEND = "WEEKEND"


class CircuitBreaker(str, Enum):
    DAILY_LOSS = "DAILY_LOSS"
    CONSECUTIVE_LOSSES = "CONSECUTIVE_LOSSES"
    WEEKLY_DRAWDOWN = "WEEKLY_DRAWDOWN"
    TOTAL_DRAWDOWN = "TOTAL_DRAWDOWN"
    MIN_BALANCE = "MIN_BALANCE"
    KILL_SWITCH = "KILL_SWITCH"


class ExitReason(str, Enum):
    SL_HIT = "SL_HIT"
    TP_HIT = "TP_HIT"
    TRAILING_STOP = "TRAILING_STOP"
    PARTIAL_CLOSE = "PARTIAL_CLOSE"
    MAX_DURATION = "MAX_DURATION"
    SWAP_CLOSE = "SWAP_CLOSE"
    WEEKEND_CLOSE = "WEEKEND_CLOSE"
    CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
    KILL_SWITCH = "KILL_SWITCH"
    MANUAL = "MANUAL"
    REGIME_SHIFT = "REGIME_SHIFT"


# Timeframe codes used by MT5
MT5_TIMEFRAMES = {
    "M1": 1, "M5": 5, "M15": 15, "M30": 30,
    "H1": 16385, "H4": 16388, "D1": 16408, "W1": 32769, "MN1": 49153,
}

# Filling modes
MT5_FILLING = {
    "FOK": 0,
    "IOC": 1,
    "RETURN": 2,
}

# Order types
ORDER_TYPE_BUY = 0
ORDER_TYPE_SELL = 1

# Trade return codes (subset we care about)
TRADE_RETCODE_DONE = 10009
TRADE_RETCODE_REQUOTE = 10004
TRADE_RETCODE_REJECT = 10006
TRADE_RETCODE_INVALID_STOPS = 10016
TRADE_RETCODE_NO_MONEY = 10019
TRADE_RETCODE_PRICE_CHANGED = 10020
TRADE_RETCODE_PRICE_OFF = 10021
TRADE_RETCODE_MARKET_CLOSED = 10018
TRADE_RETCODE_DONE_PARTIAL = 10010
